### ISSUE TITLE
error: ‘cuckoo_time_translator::UnwrappedStamp::UnwrappedStamp(uint64_t)’ is private

### ISSUE THREAD

**Issue by rikba** [ethz-asl/cuckoo_time_translator#53]
Hi @HannesSommer 

Thanks again for your framework!

When calling 
```ros::Time stamp = device_time_translator_->translate(msg.stamp);``` 
where
`msg.stamp` is [std_msgs/Time](http://docs.ros.org/melodic/api/std_msgs/html/msg/Time.html) and
`device_time_translator_` is `std::unique_ptr<cuckoo_time_translator::DefaultDeviceTimeUnwrapperAndTranslator>` 
we get the error:
```
In file included from /home/rikba/catkin_ws/src/cuckoo_time_translator/cuckoo_time_translator_algorithms/include/cuckoo_time_translator/TimestampUnwrapper.h:6:0,
                 from /home/rikba/catkin_ws/src/cuckoo_time_translator/cuckoo_time_translator/include/cuckoo_time_translator/DeviceTimeTranslator.h:12,
                 from /home/rikba/catkin_ws/src/mav_findmine/libs/fm_time_sync/include/fm_time_sync/relay.h:6,
                 from /home/rikba/catkin_ws/src/mav_findmine/libs/fm_time_sync/src/relay.cc:1:
/home/rikba/catkin_ws/src/cuckoo_time_translator/cuckoo_time_translator_algorithms/include/cuckoo_time_translator/ClockParameters.h: In member function ‘void fm_time_sync::Relay::processULandingMicroCallback(const ULandingMicro&)’:
/home/rikba/catkin_ws/src/cuckoo_time_translator/cuckoo_time_translator_algorithms/include/cuckoo_time_translator/ClockParameters.h:18:3: error: ‘cuckoo_time_translator::UnwrappedStamp::UnwrappedStamp(uint64_t)’ is private
   UnwrappedStamp(uint64_t stamp) : stamp_(stamp){}
   ^
/home/rikba/catkin_ws/src/mav_findmine/libs/fm_time_sync/src/relay.cc:229:51: error: within this context
       device_time_translator_->translate(msg.stamp);
                                                   ^
make[2]: *** [CMakeFiles/fm_time_sync.dir/src/relay.cc.o] Error 1
make[1]: *** [CMakeFiles/fm_time_sync.dir/all] Error 2
make: *** [all] Error 2
```

No pressure but whenever you have time we would be happy to get some feedback.

**Comment by HannesSommer** [comment]
I believe this is a wrong usage. If you are having a ROS time you probably don't have to unwrap it (unwrapping is more for hardware counters that wrap frequently). What you probably want instead is a `UnwrappedDeviceTimeTranslator`.

**Comment by rikba** [comment]
Sorry, I did a wrong problem formulation. 
`msg.stamp` is `uint32`, our hardware timestamp in micro seconds.

**Comment by HannesSommer** [comment]
Ah, okay. And you only want to translate? I.e. you don't want to update the translator? (updating you would do with https://github.com/ethz-asl/cuckoo_time_translator/blob/a241127c5f942c75652450440c37f8cc332e1dbd/cuckoo_time_translator/include/cuckoo_time_translator/DeviceTimeTranslator.h#L138).

If so you would need to use https://github.com/ethz-asl/cuckoo_time_translator/blob/a241127c5f942c75652450440c37f8cc332e1dbd/cuckoo_time_translator/include/cuckoo_time_translator/DeviceTimeTranslator.h#L150 to unwrap the `msg.stamp` first (that is what the typing is trying to ensure). 
Beware of the constraints regarding unwrapping: the algorithm relies on unwrapp being called in strict temporal order of the timestamped events (see also doc comment of this function). That is why it is quite uncommon that you only want to translate while unwrapping. The only reason I can think of is that for some reason you don't have a sufficiently good receive time associated with the event or different channels to receive messages from the same clock with different mean transport delay.
 
Maybe there is a misconception somewhere? To catch these the library is typed so rigorously...

**Comment by rikba** [comment]
Maybe I should elaborate our setup for you to see if it makes sense.
![findmine_deployment 8](https://user-images.githubusercontent.com/11293852/50146266-a7da1680-02b3-11e9-8897-6adf56b88dca.png)
We readout several sensors / sensor timestamps on a microcontroller, set the microcontroller clock time on receive time, send the data via serial to a computer and translate the timestamp into the computer clock time.

Our thought was that we only update the cuckoo filter on the IMU message (or even a PPS signal from the arduino) where we can insure the same transport / frequency. All other message timestamps then only get translated.

**Comment by rikba** [comment]
> or different channels to receive messages from the same clock with different mean transport delay.
I guess this fits our case?

**Comment by HannesSommer** [comment]
Ah. Thanks. Awesome diagram :). Yes, I think you are pretty much in that case. So, you need the separate unwrap. Just make sure that you call it in the order in which the packages arrive through the serial connection.

However, since you seem to have the micro controller under your control I see more accurate alternatives:
1. Setup independent two way sync on the serial channel.
2. Add a transmission timestamp to the message (this library also supports that : https://github.com/ethz-asl/cuckoo_time_translator/blob/a241127c5f942c75652450440c37f8cc332e1dbd/cuckoo_time_translator/include/cuckoo_time_translator/DeviceTimeTranslator.h#L183 ). For instance you could read the micro-controllers clock right before you send the first  byte through the serial connection and send this value as a transmission timestamp. On the receive side you only must make sure that you read the CPU clock on the first byte received. This you could do for all messages no matter how big.

But I guess using the IMU message is also a good start. And you are very close to that solution.Maybe keep the alternatives in mind in case you are not happy with the result.

**Comment by rikba** [comment]
Thanks for your comments! We will first try the oneway unwrapping strategy and if we have time (or it is unsufficient) we will try to use this library with transmission timestamps.

> Btw. in you image I can't see RS232 or similar connections on the computer. Are you using a USB to RS232 adapter?

We use a [UDOO x86 Ultra](http://www.seco.com/misk/UDOO_X86_datasheet.pdf) which has an embedded Intel Curie microcontroller. [The communications between the Braswell SOC and the CurieTM SOC come through a USB interface, exactly like Arduino 101 / Genuino 101 boards connect to external PCs.](https://www.udoo.org/docs-x86/Hardware_Reference/Overview.html). Any opinion on the [Quark USB interface](https://www.intel.com/content/dam/support/us/en/documents/boardsandkits/curie/intel-curie-module-datasheet.pdf)?

**Comment by HannesSommer** [comment]
Ah, interesting! Thanks for the links. Actually this design looks quite troublesome to me timing wise. So sad. The SoC has two UARTs (typically very low latency) but instead of using one of them for the link they use USB that gets probably converted to a serial signal anyway because otherwise it wouldn't be like an Arduino.. Unbelievable.
 
On the bright side it seems like a dedicated USB port. Hence, the random delays are probably around 10ms (wild guessing). Eventually you might want to do a simple ping test from the SoC to the uC and back and observe the randomness of the two way latency.

If it is all to bad I would look into creating second link through one of the UARTs, that comes out of the expansion connector 2. You can probably connect it to the digital IO of the mC and create a proper serial connection with low latency (probably below 1 micro second) that you can use for synchronization.
If that is too much work you could have a look increasing USB polling rate -- because that is what happens prior to USB3.0 : the devices get polled for new events! But the polling is not the only timing problem with USB on Linux...
